using System;

namespace Valve.VR
{
	public enum EVREventType
	{
		VREvent_None,
		VREvent_TrackedDeviceActivated = 100,
		VREvent_TrackedDeviceDeactivated,
		VREvent_TrackedDeviceUpdated,
		VREvent_TrackedDeviceUserInteractionStarted,
		VREvent_TrackedDeviceUserInteractionEnded,
		VREvent_IpdChanged,
		VREvent_EnterStandbyMode,
		VREvent_LeaveStandbyMode,
		VREvent_TrackedDeviceRoleChanged,
		VREvent_ButtonPress = 200,
		VREvent_ButtonUnpress,
		VREvent_ButtonTouch,
		VREvent_ButtonUntouch,
		VREvent_MouseMove = 300,
		VREvent_MouseButtonDown,
		VREvent_MouseButtonUp,
		VREvent_FocusEnter,
		VREvent_FocusLeave,
		VREvent_Scroll,
		VREvent_TouchPadMove,
		VREvent_InputFocusCaptured = 400,
		VREvent_InputFocusReleased,
		VREvent_SceneFocusLost,
		VREvent_SceneFocusGained,
		VREvent_SceneApplicationChanged,
		VREvent_SceneFocusChanged,
		VREvent_HideRenderModels = 410,
		VREvent_ShowRenderModels,
		VREvent_OverlayShown = 500,
		VREvent_OverlayHidden,
		VREvent_DashboardActivated,
		VREvent_DashboardDeactivated,
		VREvent_DashboardThumbSelected,
		VREvent_DashboardRequested,
		VREvent_ResetDashboard,
		VREvent_RenderToast,
		VREvent_ImageLoaded,
		VREvent_ShowKeyboard,
		VREvent_HideKeyboard,
		VREvent_OverlayGamepadFocusGained,
		VREvent_OverlayGamepadFocusLost,
		VREvent_Notification_Shown = 600,
		VREvent_Notification_Hidden,
		VREvent_Notification_BeginInteraction,
		VREvent_Notification_Destroyed,
		VREvent_Quit = 700,
		VREvent_ProcessQuit,
		VREvent_QuitAborted_UserPrompt,
		VREvent_QuitAcknowledged,
		VREvent_ChaperoneDataHasChanged = 800,
		VREvent_ChaperoneUniverseHasChanged,
		VREvent_ChaperoneTempDataHasChanged,
		VREvent_ChaperoneSettingsHaveChanged,
		VREvent_SeatedZeroPoseReset,
		VREvent_BackgroundSettingHasChanged = 850,
		VREvent_CameraSettingsHaveChanged,
		VREvent_StatusUpdate = 900,
		VREvent_MCImageUpdated = 1000,
		VREvent_FirmwareUpdateStarted = 1100,
		VREvent_FirmwareUpdateFinished,
		VREvent_KeyboardClosed = 1200,
		VREvent_KeyboardCharInput,
		VREvent_KeyboardDone,
		VREvent_ApplicationTransitionStarted = 1300,
		VREvent_ApplicationTransitionAborted,
		VREvent_ApplicationTransitionNewAppStarted,
		VREvent_Compositor_MirrorWindowShown = 1400,
		VREvent_Compositor_MirrorWindowHidden,
		VREvent_Compositor_ChaperoneBoundsShown = 1410,
		VREvent_Compositor_ChaperoneBoundsHidden,
		VREvent_TrackedCamera_StartVideoStream = 1500,
		VREvent_TrackedCamera_StopVideoStream,
		VREvent_TrackedCamera_PauseVideoStream,
		VREvent_TrackedCamera_ResumeVideoStream,
		VREvent_PerformanceTest_EnableCapture = 1600,
		VREvent_PerformanceTest_DisableCapture,
		VREvent_PerformanceTest_FidelityLevel,
		VREvent_VendorSpecific_Reserved_Start = 10000,
		VREvent_VendorSpecific_Reserved_End = 19999
	}
}
