using System;

namespace FMOD
{
	public enum DSP_PAN
	{
		MODE,
		STEREO_POSITION,
		SURROUND_DIRECTION,
		SURROUND_EXTENT,
		SURROUND_ROTATION,
		SURROUND_LFE_LEVEL,
		SURROUND_FROM_STEREO_MODE,
		SURROUND_STEREO_SEPARATION,
		SURROUND_STEREO_AXIS,
		ENABLED_SURROUND_SPEAKERS,
		_3D_POSITION,
		_3D_ROLLOFF,
		_3D_MIN_DISTANCE,
		_3D_MAX_DISTANCE,
		_3D_EXTENT_MODE,
		_3D_SOUND_SIZE,
		_3D_MIN_EXTENT,
		_3D_PAN_BLEND,
		LFE_UPMIX_ENABLED,
		OVERALL_GAIN,
		SURROUND_SPEAKER_MODE
	}
}
