using System;

namespace FMOD
{
	public enum DSP_PARAMETER_FLOAT_MAPPING_TYPE
	{
		DSP_PARAMETER_FLOAT_MAPPING_TYPE_LINEAR,
		DSP_PARAMETER_FLOAT_MAPPING_TYPE_AUTO,
		DSP_PARAMETER_FLOAT_MAPPING_TYPE_PIECEWISE_LINEAR
	}
}
