using System;

namespace FMOD
{
	public enum DSP_PARAMETER_DATA_TYPE
	{
		DSP_PARAMETER_DATA_TYPE_USER,
		DSP_PARAMETER_DATA_TYPE_OVERALLGAIN = -1,
		DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES = -2,
		DSP_PARAMETER_DATA_TYPE_SIDECHAIN = -3,
		DSP_PARAMETER_DATA_TYPE_FFT = -4,
		DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI = -5
	}
}
