using System;

namespace FMOD.Studio
{
	public enum PARAMETER_TYPE
	{
		GAME_CONTROLLED,
		AUTOMATIC_DISTANCE,
		AUTOMATIC_EVENT_CONE_ANGLE,
		AUTOMATIC_EVENT_ORIENTATION,
		AUTOMATIC_DIRECTION,
		AUTOMATIC_ELEVATION,
		AUTOMATIC_LISTENER_ORIENTATION
	}
}
